- icon: "icon ion-coffee"
  title: "Branding"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-compass"
  title: "Web Design"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-image"
  title: "App Design"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-bug"
  title: "Start Up"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-headphone"
  title: "Logo Design"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-leaf"
  title: "Development"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-planet"
  title: "Brand Identity"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-earth"
  title: "Brand Identity"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-earth"
  title: "Brand Identity"
  content: "Lorem ipsum dolor sit amet."

- icon: "ion-earth"
  title: "Brand Identity"
  content: "Lorem ipsum dolor sit amet."

